server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://39.106.0.61:3306/springboot?characterEncoding=UTF-8
    username: root
    password: Root!23456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.springboot